services:
  database:
    image: mariadb:12
    restart: unless-stopped
    environment:
      MARIADB_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
      MARIADB_DATABASE: ${DB_NAME:-app}
      MARIADB_USER: ${DB_USER:-app}
      MARIADB_RANDOM_ROOT_PASSWORD: true
      TZ: Europe/Paris
    volumes:
      - database_data:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 3306:3306

volumes:
  database_data:
